Repository CoMakery/comakery-server, pull requests merged in 2021-07, with the labels that each got.

#2205 Fix specs for acceptance branch
  spec/controllers/projects_controller_spec.rb
  spec/features/dashboard/accounts/index_spec.rb
Labels: Ready to review

#2206 Update styles for transfer rules page
  app/javascript/src/application.scss
  app/views/dashboard/transfer_rules/_transfer_rule.html.erb
  app/views/dashboard/transfer_rules/index.html.erb
Labels: Ready to review

#2196 fixed icons and dropdown item color
  public/dev/styleguide/dist/css/icons.css
  public/dev/styleguide/dist/css/upside-override.css
Labels: Ready to review

#2213 Add spec admin invites admin
  spec/features/dashboard/accounts/admin_invitation_spec.rb
Labels: Ready to review

#2211 Few readme changes
  README.md
Labels: Ready to review

#2214 Add data migration to delete invalid images
  db/data_migrations/20210702070447_delete_invalid_images.rb
  spec/data_migrations/delete_invalid_images_spec.rb
Labels: Ready to review

#2221 Readme changes: imagemagick should be installed
  README.md
Labels: Ready to merge

#2219 Update accounts index spec
  spec/features/accounts/index_spec.rb
Labels: Ready to merge

#2218 HW: Show heroku deploy buttons for algorand tokens
  app/helpers/application_helper.rb
  app/models/token.rb
  app/views/dashboard/transfers/_filters.html.erb
  hotwallet/app.json
  hotwallet/lib/hotwalletUtils.js
  hotwallet/tests/checkAllVariablesAreSet.test.js
  spec/helpers/application_helper_spec.rb
Labels: Ready to merge

#2210 Check confidentiality for whitelabel
  app/controllers/application_controller.rb
  app/decorators/project_decorator.rb
  app/models/project.rb
  app/policies/project_policy.rb
  spec/policies/project_policy_spec.rb
Labels: Ready to merge

#2220 Improve Awards data integrity for CSV export
  app/decorators/award_decorator.rb
  app/models/award.rb
  db/data_migrations/20210629004508_populate_recipient_wallet_for_awards.rb
  spec/data_migrations/20210629004508_populate_recipient_wallet_for_awards_spec.rb
  spec/factories/award_types.rb
  spec/factories/awards.rb
  spec/factories/blockchain_transactions.rb
  spec/factories/projects.rb
  spec/factories/tokens.rb
  spec/factories/wallets.rb
Labels: Ready to merge

#2215 Dynamically trim ABI for OREID requests
  app/lib/comakery/eth/tx/erc20.rb
  db/seeds.rb
  spec/factories/projects.rb
  spec/factories/tokens.rb
  spec/lib/comakery/eth/tx/erc20_spec.rb
  spec/vcr/Comakery_Eth_Tx_Erc20/_valid_/for_correct_transaction/1_14_3_1.yml
  spec/vcr/Comakery_Eth_Tx_Erc20/_valid_/for_transaction_with_incorrect_method_id/1_14_1_1.yml
  spec/vcr/Comakery_Eth_Tx_Erc20/_valid_/for_transaction_with_incorrect_method_params/1_14_2_1.yml
  spec/vcr/Comakery_Eth_Tx_Erc20/_valid_amount_/1_11_1.yml
  spec/vcr/Comakery_Eth_Tx_Erc20/_valid_method_id_/1_12_1.yml
  spec/vcr/Comakery_Eth_Tx_Erc20/_valid_method_params_/1_13_1.yml
  spec/vcr/Comakery_Eth_Tx_Erc20/_valid_to_/1_10_1.yml
Labels: Ready to merge

#2223 Fix acceptance specs
  spec/factories/wallets.rb
Labels: Ready to merge

#2222 Update hotwallet branch
  app.json
  lib/hotwalletUtils.js
  tests/checkAllVariablesAreSet.test.js
  yarn.lock
Labels: Ready to merge

#2209 Increase invite token length
  app/models/invite.rb
  db/migrate/20210701142532_change_token_limit.rb
  db/schema.rb
  erd.pdf
  spec/controllers/invites_controller_spec.rb
  spec/models/invite_spec.rb
Labels: Ready to merge

#2229 Improve awards data migration
  app/models/award.rb
  db/data_migrations/20210629004508_populate_recipient_wallet_for_awards.rb
  spec/data_migrations/20210629004508_populate_recipient_wallet_for_awards_spec.rb
Labels: Ready to review

#2204 Creating new user or editing permission of the existing user breaks the Accounts table design
  app/controllers/application_controller.rb
  app/controllers/projects/accounts/settings_controller.rb
  app/javascript/controllers/accept_turbo_stream_controller.js
  app/javascript/src/application.scss
  app/models/project_role.rb
  app/views/dashboard/accounts/_account.html.erb
  app/views/projects/accounts/settings/show.html.erb
  config/routes.rb
  spec/controllers/projects/accounts/settings_controller_spec.rb
  spec/features/dashboard/accounts/settings_spec.rb
Labels: Ready to merge

#2230 Optimize PopulateRecipientWalletForAwards data migration
  db/data_migrations/20210629004508_populate_recipient_wallet_for_awards.rb
  db/data_migrations/20210702070447_delete_invalid_images.rb
Labels: Ready to merge

#2225 Clear existing transfer rules before sync from blockchain
  app/controllers/dashboard/transfer_rules_controller.rb
Labels: Ready to merge, Ready to review

#2235 Fix accounts/add_person_spec.rb
  spec/support/capybara.rb
Labels: Ready to merge

#2224 More tests fixes
  .github/workflows/rspec.yml
  Gemfile.lock
  config/environments/test.rb
  spec/controllers/contributors_controller_spec.rb
Labels: Ready to merge, Ready to review

#2232 Fix settings lazy load
  app/controllers/projects/accounts/settings_controller.rb
Labels: Ready to review

#2228 Fix display burn transfers
  app/controllers/dashboard/transfers_controller.rb
  spec/controllers/dashboard/transfers_controller_spec.rb
  spec/features/transfers/create_spec.rb
Labels: Ready to review

#2226 Wallet changes for nil blockchain
  app/models/wallet.rb
  spec/controllers/api/v1/wallets_controller_spec.rb
Labels: Ready to review

#2212 Grant project member role to transfer recipient
  app/models/award.rb
  spec/controllers/projects_controller_spec.rb
  spec/models/award_spec.rb
  spec/policies/project_policy_spec.rb
Labels: Ready to review

#2241 Require whitelabel invitation
  app/controllers/accounts_controller.rb
  app/controllers/application_controller.rb
  app/controllers/auth/eth_controller.rb
  app/controllers/invites_controller.rb
  app/controllers/missions_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/unsubscription_controller.rb
  app/javascript/components/MissionForm.jsx
  db/migrate/20210705191139_add_require_invitation_to_mission.rb
  db/schema.rb
  erd.pdf
  spec/acceptance/ui/whitelabel/require_invitation_spec.rb
  spec/controllers/application_controller_spec.rb
  spec/javascript/components/__snapshots__/MissionForm.spec.js.snap
  spec/support/mom.rb
Labels: Ready to review

#2245 models coverage score improvement
  app/models/project.rb
  app/policies/project_policy.rb
  spec/factories/project_roles.rb
  spec/models/project_spec.rb
Labels: Ready to merge

#2231 Setup HTML proofer
  Gemfile
  Gemfile.lock
  app/views/accounts/index.html.erb
  app/views/dashboard/transfer_types/index.html.erb
  config/application.rb
  config/initializers/html_proofer.rb
  erd.pdf
  spec/features/accounts/index_spec.rb
  spec/rails_helper.rb
  spec/support/mom.rb
Labels: Ready to review

#2250 Use whitelabel mission when sending invites
  app/interactors/send_invite.rb
  app/views/user_mailer/send_invite_to_platform.html.erb
  spec/mailers/user_mailer_spec.rb
Labels: Ready to review

#2249 Improve OREID payment integration
  app/controllers/dashboard/accounts_controller.rb
  app/controllers/wallets_controller.rb
  app/javascript/controllers/sign/ore_id_controller.js
  app/views/dashboard/accounts/_account.html.erb
  app/views/dashboard/accounts/index.html.erb
  app/views/dashboard/transfer_rules/_form_transfer_rule.html.erb
  app/views/dashboard/transfer_rules/_transfer_rule.html.erb
  app/views/dashboard/transfer_rules/index.html.erb
  app/views/dashboard/transfers/index.html.erb
  spec/controllers/wallets_controller_spec.rb
  spec/features/dashboard/accounts/add_person_spec.rb
  spec/features/dashboard/accounts/index_spec.rb
  spec/features/dashboard/transfers/batch_size_spec.rb
  spec/features/dashboard/wallet_connect_spec.rb
Labels: Ready to review

#2251 Fix invitation logic issues
  app/controllers/accounts_controller.rb
  app/controllers/invites_controller.rb
  app/controllers/password_resets_controller.rb
  app/controllers/projects_controller.rb
  app/models/account.rb
  app/models/invite.rb
  spec/acceptance/ui/whitelabel/require_invitation_spec.rb
  spec/controllers/accounts_controller_spec.rb
  spec/controllers/invites_controller_spec.rb
  spec/features/accounts/create_spec.rb
  spec/features/dashboard/transfers/batch_size_spec.rb
  spec/models/account_spec.rb
  spec/models/invite_spec.rb
Labels: Ready to review

#2246 Update transfers csv columns
  app/decorators/award_decorator.rb
  spec/decorators/award_decorator_spec.rb
Labels: Ready to review

#2248 Transfer settings menu
  app/controllers/projects/transfers/settings_controller.rb
  app/javascript/controllers/transfer_settings_controller.js
  app/views/dashboard/transfers/_transfer.html.erb
  app/views/projects/transfers/settings/show.html.erb
  config/routes.rb
  spec/controllers/transfers/settings_controller_spec.rb
  spec/features/dashboard/transfers/settings/show_spec.rb
  spec/features/dashboard/transfers/transfer_prioritize_button_spec.rb
Labels: Ready to review

#2227 Project tasks visibility
  app/controllers/award_types_controller.rb
  app/controllers/awards_controller.rb
  app/controllers/missions_controller.rb
  app/decorators/project_decorator.rb
  app/javascript/components/MissionForm.jsx
  app/javascript/components/layouts/Header.jsx
  app/javascript/components/layouts/ProjectSetupHeader.jsx
  app/policies/award_policy.rb
  app/policies/award_type_policy.rb
  app/policies/project_policy.rb
  app/views/layouts/application.html.erb
  app/views/layouts/legacy.html.rb
  db/migrate/20210706104324_add_project_awards_visible_to_missions.rb
  db/schema.rb
  spec/controllers/awards_controller_spec.rb
  spec/features/award_types/index_spec.rb
  spec/features/comakery_admin/admin_tabs_spec.rb
  spec/features/tasks/project_tasks.spec.rb
  spec/javascript/components/MissionForm.spec.js
  spec/javascript/components/__snapshots__/MissionForm.spec.js.snap
  spec/policies/project_policy_spec.rb
  spec/support/mom.rb
Labels: Ready to merge

#2254 Add `RepublicAccountRecoveryEnvironment` param for OREID token
  .github/workflows/rspec.yml
  app.json
  app/models/ore_id_service.rb
  spec/models/ore_id_service_spec.rb
  spec/vcr/ore_id_service/token_recovery_default.yml
  spec/vcr/ore_id_service/token_recovery_prod.yml
Labels: Ready to review

#2256 Fix images in `MissionForm`
  app/controllers/missions_controller.rb
  spec/controllers/missions_controller_spec.rb
  spec/features/dashboard/accounts/index_spec.rb
  spec/support/mom.rb
Labels: Ready to review

#2255 Use decorated role names in emails
  app/decorators/project_role_decorator.rb
  app/helpers/project_roles_helper.rb
  app/models/project_role.rb
  app/views/dashboard/accounts/_account.html.erb
  app/views/projects/accounts/permissions/_modal.html.erb
  app/views/projects/invites/_modal.html.erb
  app/views/user_mailer/send_invite_to_platform.html.erb
  app/views/user_mailer/send_invite_to_project.html.erb
  spec/decorators/project_role_decorator_spec.rb
  spec/mailers/user_mailer_spec.rb
Labels: Ready to review

#2260 Fix cancelled filter spec
  spec/features/dashboard/transfers/filters/cancelled_filter_spec.rb
Labels: Ready to review

#2263 Fix project creation
  app/javascript/components/BatchForm.jsx
  app/javascript/components/MissionForm.jsx
  app/javascript/components/ProjectForm.jsx
  app/javascript/components/TaskForm.jsx
  app/javascript/components/TaskShow.jsx
  app/javascript/components/TokenForm.jsx
  app/javascript/components/utils.js
  spec/features/projects/new_spec.rb
Labels: Ready to review

#2261 Update batch size input spec
  spec/features/dashboard/transfers/batch_size_spec.rb
Labels: Ready to review

#2265 seeds_spec: Fix cleanup DB after seeds load
  spec/tasks/seeds_spec.rb
Labels: Ready to merge

#2268 Optimize three dots menu settings spec
  spec/features/dashboard/accounts/index_spec.rb
Labels: Ready to review
