Repository CoMakery/comakery-server, pull requests merged in 2021-03, with the labels that each got.

#1955 Fix transfer's order in case of set priority
  app/models/concerns/blockchain_transactable.rb
  spec/controllers/api/v1/blockchain_transactions_controller_spec.rb
  spec/vcr/Api_V1_BlockchainTransactionsController/POST_create/with_awards_available_for_transaction/with_request_from_a_hot_wallet/with_registered_hw_and_hot_wallet_mode_is_auto_sending_with_prioritized_transfer/creates_the_prioritized_transaction.yml
Labels: Ready to merge

#1957 Improve error details on OREID account creation
  app/models/ore_id_service.rb
Labels: Ready to review

#1936 Issue#1933 transfer page chart query speed
  app/assets/images/spinner.gif
  app/controllers/dashboard/transfers_controller.rb
  app/decorators/project_decorator.rb
  app/helpers/application_helper.rb
  app/javascript/components/TransfersCalendar.jsx
  app/javascript/src/application.scss
  app/views/dashboard/transfers/_chart.html.erb
  app/views/dashboard/transfers/_filter_status.html.erb
  app/views/dashboard/transfers/_filters.html.erb
  app/views/dashboard/transfers/_summary.html.erb
  app/views/dashboard/transfers/_transfer.html.erb
  app/views/dashboard/transfers/index.html.erb
  app/views/shared/_transfer_button.html.erb
  config/routes.rb
  spec/features/dashboard/transfers/filters/aml_kyc_failed_filter_spec.rb
  spec/features/dashboard/transfers/filters/aml_kyc_unknown_filter_spec.rb
  spec/features/dashboard/transfers/filters/cancelled_filter_spec.rb
  spec/features/dashboard/transfers/filters/needs_wallet_filter_spec.rb
  spec/features/dashboard/transfers/filters/ready_filter_spec.rb
  spec/features/dashboard/transfers/filters/transferred_filter_spec.rb
  spec/features/dashboard/transfers/index_page_spec.rb
Labels: Ready to merge

#1958 Bump mimemagic gem
  Gemfile.lock
Labels: Ready to merge

#1956 Recovery token lifetime
  app/controllers/api/v1/wallet_recovery_controller.rb
  app/models/api_ore_id_wallet_recovery.rb
  app/models/api_request_log.rb
  spec/controllers/api/v1/wallet_recovery_controller_spec.rb
Labels: Ready to review

#1960 Fix bundler's dependencies
  .github/workflows/rspec.yml
  Gemfile.lock
Labels: Ready to merge

#1967 Recovery Service updates
  app/controllers/api/v1/wallets_controller.rb
  app/models/ore_id_service.rb
  spec/acceptance/api/v1/19_wallets_spec.rb
  spec/controllers/api/v1/wallets_controller_spec.rb
  spec/models/ore_id_service_spec.rb
  spec/vcr/OreIdService/_reset_url/1_9_1.yml
  spec/vcr/ore_id_service/token_for_recovery.yml
Labels: Ready to review

#1969 Recovery service: Use wallet_recovery_api_public_key to verify a signature
  app/controllers/api/v1/concerns/requires_recovery_signature.rb
  app/controllers/api/v1/wallet_recovery_controller.rb
  app/controllers/missions_controller.rb
  app/models/mission.rb
  erd.pdf
  spec/acceptance/api/v1/22_wallet_recovery_spec.rb
  spec/controllers/api/v1/concerns/requires_recovery_signature_spec.rb
  spec/controllers/api/v1/wallet_recovery_controller_spec.rb
  spec/models/mission_spec.rb
Labels: Ready to merge, Ready to review

#1968 Recovery Service: Updated ECIES encryption logic
  app/controllers/api/v1/wallet_recovery_controller.rb
  app/controllers/api/v1/wallets_controller.rb
  app/models/api_ore_id_wallet_recovery.rb
  spec/acceptance/api/v1/22_wallet_recovery_spec.rb
  spec/controllers/api/v1/wallet_recovery_controller_spec.rb
  spec/controllers/api/v1/wallets_controller_spec.rb
  spec/models/api_ore_id_wallet_recovery_spec.rb
Labels: Ready to review

#1950 Recaptcha
  Gemfile
  Gemfile.lock
  app.json
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/recaptcha.scss
  app/controllers/accounts_controller.rb
  app/controllers/sessions_controller.rb
  app/interactors/accounts/authenticate.rb
  app/interactors/accounts/initialize.rb
  app/views/accounts/new.html.rb
  app/views/sessions/new.html.rb
  app/views/shared/_recaptcha.html.erb
  config/initializers/recaptcha.rb
  spec/interactors/accounts/authenticate_spec.rb
  spec/interactors/accounts/initialize_spec.rb
Labels: Ready to merge

#1977 Fix secrets param format for OREID app-token
  app/models/ore_id_service.rb
  spec/vcr/ore_id_service/token_for_recovery.yml
Labels: Ready to merge

#1979 Update OREID app-token secret format
  app/models/ore_id_service.rb
  spec/vcr/ore_id_service/token_for_recovery.yml
Labels: Ready to merge

#1978 Whitelabel missions should not be visible on comakery
  app/controllers/pages_controller.rb
  app/models/mission.rb
  app/policies/mission_policy.rb
  spec/policies/mission_policy_spec.rb
Labels: Ready to merge

#1971 API password reset url returns 500 for non ore id wallets
  app/controllers/api/v1/wallets_controller.rb
  spec/controllers/api/v1/wallets_controller_spec.rb
Labels: Ready to merge

#1980 Add intergation tests for wallet configuration flow
  spec/acceptance/api/v1/24_wallet_configuration_flow_spec.rb
  spec/requests/api/v1/wallet_configuration_flow_spec.rb
  spec/vcr/wallet_configuration_flow/password_reset.yml
  spec/vcr/wallet_configuration_flow/sync_ore_id.yml
Labels: Ready to review
